// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.smart.retailing.multi.kafka.starter.proto;

public final class DemoPb {
  private DemoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trpc.wechat.search.data.PbMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string routekey = 1;</code>
     * @return Whether the routekey field is set.
     */
    boolean hasRoutekey();
    /**
     * <code>optional string routekey = 1;</code>
     * @return The routekey.
     */
    java.lang.String getRoutekey();
    /**
     * <code>optional string routekey = 1;</code>
     * @return The bytes for routekey.
     */
    com.google.protobuf.ByteString
        getRoutekeyBytes();

    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return Whether the cosImgUrl field is set.
     */
    boolean hasCosImgUrl();
    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return The cosImgUrl.
     */
    java.lang.String getCosImgUrl();
    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return The bytes for cosImgUrl.
     */
    com.google.protobuf.ByteString
        getCosImgUrlBytes();

    /**
     * <code>optional string base64str = 3;</code>
     * @return Whether the base64str field is set.
     */
    boolean hasBase64Str();
    /**
     * <code>optional string base64str = 3;</code>
     * @return The base64str.
     */
    java.lang.String getBase64Str();
    /**
     * <code>optional string base64str = 3;</code>
     * @return The bytes for base64str.
     */
    com.google.protobuf.ByteString
        getBase64StrBytes();
  }
  /**
   * Protobuf type {@code trpc.wechat.search.data.PbMsg}
   */
  public static final class PbMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trpc.wechat.search.data.PbMsg)
      PbMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbMsg.newBuilder() to construct.
    private PbMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbMsg() {
      routekey_ = "";
      cosImgUrl_ = "";
      base64Str_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PbMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              routekey_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              cosImgUrl_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              base64Str_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smart.retailing.multi.kafka.starter.proto.DemoPb.internal_static_trpc_wechat_search_data_PbMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smart.retailing.multi.kafka.starter.proto.DemoPb.internal_static_trpc_wechat_search_data_PbMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.class, com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.Builder.class);
    }

    private int bitField0_;
    public static final int ROUTEKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object routekey_;
    /**
     * <code>optional string routekey = 1;</code>
     * @return Whether the routekey field is set.
     */
    @java.lang.Override
    public boolean hasRoutekey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string routekey = 1;</code>
     * @return The routekey.
     */
    @java.lang.Override
    public java.lang.String getRoutekey() {
      java.lang.Object ref = routekey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          routekey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string routekey = 1;</code>
     * @return The bytes for routekey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoutekeyBytes() {
      java.lang.Object ref = routekey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routekey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COSIMGURL_FIELD_NUMBER = 2;
    private volatile java.lang.Object cosImgUrl_;
    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return Whether the cosImgUrl field is set.
     */
    @java.lang.Override
    public boolean hasCosImgUrl() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return The cosImgUrl.
     */
    @java.lang.Override
    public java.lang.String getCosImgUrl() {
      java.lang.Object ref = cosImgUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cosImgUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cosImgUrl = 2;</code>
     * @return The bytes for cosImgUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCosImgUrlBytes() {
      java.lang.Object ref = cosImgUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cosImgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE64STR_FIELD_NUMBER = 3;
    private volatile java.lang.Object base64Str_;
    /**
     * <code>optional string base64str = 3;</code>
     * @return Whether the base64str field is set.
     */
    @java.lang.Override
    public boolean hasBase64Str() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string base64str = 3;</code>
     * @return The base64str.
     */
    @java.lang.Override
    public java.lang.String getBase64Str() {
      java.lang.Object ref = base64Str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          base64Str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string base64str = 3;</code>
     * @return The bytes for base64str.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBase64StrBytes() {
      java.lang.Object ref = base64Str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        base64Str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, routekey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cosImgUrl_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, base64Str_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, routekey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cosImgUrl_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, base64Str_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg)) {
        return super.equals(obj);
      }
      com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg other = (com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg) obj;

      if (hasRoutekey() != other.hasRoutekey()) return false;
      if (hasRoutekey()) {
        if (!getRoutekey()
            .equals(other.getRoutekey())) return false;
      }
      if (hasCosImgUrl() != other.hasCosImgUrl()) return false;
      if (hasCosImgUrl()) {
        if (!getCosImgUrl()
            .equals(other.getCosImgUrl())) return false;
      }
      if (hasBase64Str() != other.hasBase64Str()) return false;
      if (hasBase64Str()) {
        if (!getBase64Str()
            .equals(other.getBase64Str())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoutekey()) {
        hash = (37 * hash) + ROUTEKEY_FIELD_NUMBER;
        hash = (53 * hash) + getRoutekey().hashCode();
      }
      if (hasCosImgUrl()) {
        hash = (37 * hash) + COSIMGURL_FIELD_NUMBER;
        hash = (53 * hash) + getCosImgUrl().hashCode();
      }
      if (hasBase64Str()) {
        hash = (37 * hash) + BASE64STR_FIELD_NUMBER;
        hash = (53 * hash) + getBase64Str().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trpc.wechat.search.data.PbMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trpc.wechat.search.data.PbMsg)
        com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smart.retailing.multi.kafka.starter.proto.DemoPb.internal_static_trpc_wechat_search_data_PbMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smart.retailing.multi.kafka.starter.proto.DemoPb.internal_static_trpc_wechat_search_data_PbMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.class, com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.Builder.class);
      }

      // Construct using com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        routekey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cosImgUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        base64Str_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smart.retailing.multi.kafka.starter.proto.DemoPb.internal_static_trpc_wechat_search_data_PbMsg_descriptor;
      }

      @java.lang.Override
      public com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg getDefaultInstanceForType() {
        return com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg build() {
        com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg buildPartial() {
        com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg result = new com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.routekey_ = routekey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cosImgUrl_ = cosImgUrl_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.base64Str_ = base64Str_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg) {
          return mergeFrom((com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg other) {
        if (other == com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg.getDefaultInstance()) return this;
        if (other.hasRoutekey()) {
          bitField0_ |= 0x00000001;
          routekey_ = other.routekey_;
          onChanged();
        }
        if (other.hasCosImgUrl()) {
          bitField0_ |= 0x00000002;
          cosImgUrl_ = other.cosImgUrl_;
          onChanged();
        }
        if (other.hasBase64Str()) {
          bitField0_ |= 0x00000004;
          base64Str_ = other.base64Str_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object routekey_ = "";
      /**
       * <code>optional string routekey = 1;</code>
       * @return Whether the routekey field is set.
       */
      public boolean hasRoutekey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string routekey = 1;</code>
       * @return The routekey.
       */
      public java.lang.String getRoutekey() {
        java.lang.Object ref = routekey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            routekey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string routekey = 1;</code>
       * @return The bytes for routekey.
       */
      public com.google.protobuf.ByteString
          getRoutekeyBytes() {
        java.lang.Object ref = routekey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routekey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string routekey = 1;</code>
       * @param value The routekey to set.
       * @return This builder for chaining.
       */
      public Builder setRoutekey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        routekey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string routekey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoutekey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        routekey_ = getDefaultInstance().getRoutekey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string routekey = 1;</code>
       * @param value The bytes for routekey to set.
       * @return This builder for chaining.
       */
      public Builder setRoutekeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        routekey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cosImgUrl_ = "";
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @return Whether the cosImgUrl field is set.
       */
      public boolean hasCosImgUrl() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @return The cosImgUrl.
       */
      public java.lang.String getCosImgUrl() {
        java.lang.Object ref = cosImgUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cosImgUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @return The bytes for cosImgUrl.
       */
      public com.google.protobuf.ByteString
          getCosImgUrlBytes() {
        java.lang.Object ref = cosImgUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cosImgUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @param value The cosImgUrl to set.
       * @return This builder for chaining.
       */
      public Builder setCosImgUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cosImgUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCosImgUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cosImgUrl_ = getDefaultInstance().getCosImgUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cosImgUrl = 2;</code>
       * @param value The bytes for cosImgUrl to set.
       * @return This builder for chaining.
       */
      public Builder setCosImgUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cosImgUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object base64Str_ = "";
      /**
       * <code>optional string base64str = 3;</code>
       * @return Whether the base64str field is set.
       */
      public boolean hasBase64Str() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string base64str = 3;</code>
       * @return The base64str.
       */
      public java.lang.String getBase64Str() {
        java.lang.Object ref = base64Str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            base64Str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string base64str = 3;</code>
       * @return The bytes for base64str.
       */
      public com.google.protobuf.ByteString
          getBase64StrBytes() {
        java.lang.Object ref = base64Str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          base64Str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string base64str = 3;</code>
       * @param value The base64str to set.
       * @return This builder for chaining.
       */
      public Builder setBase64Str(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        base64Str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string base64str = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBase64Str() {
        bitField0_ = (bitField0_ & ~0x00000004);
        base64Str_ = getDefaultInstance().getBase64Str();
        onChanged();
        return this;
      }
      /**
       * <code>optional string base64str = 3;</code>
       * @param value The bytes for base64str to set.
       * @return This builder for chaining.
       */
      public Builder setBase64StrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        base64Str_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trpc.wechat.search.data.PbMsg)
    }

    // @@protoc_insertion_point(class_scope:trpc.wechat.search.data.PbMsg)
    private static final com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg();
    }

    public static com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PbMsg>
        PARSER = new com.google.protobuf.AbstractParser<PbMsg>() {
      @java.lang.Override
      public PbMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smart.retailing.multi.kafka.starter.proto.DemoPb.PbMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trpc_wechat_search_data_PbMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trpc_wechat_search_data_PbMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\027trpc.wechat.search.data\"?\n" +
      "\005PbMsg\022\020\n\010routekey\030\001 \001(\t\022\021\n\tcosImgUrl\030\002 " +
      "\001(\t\022\021\n\tbase64str\030\003 \001(\tB7\n-com.smart.reta" +
      "iling.multi.kafka.starter.protoB\006DemoPb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trpc_wechat_search_data_PbMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trpc_wechat_search_data_PbMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trpc_wechat_search_data_PbMsg_descriptor,
        new java.lang.String[] { "Routekey", "CosImgUrl", "Base64Str", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
